[project]
name = "freshdesk-mcp"
version = "2.0.0"
description = "An MCP server for Freshdesk"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx2>=2.10.0",
    "mcp[cli]>=2.3.0,<3",
    "pydantic>=2.12",
]

[[project.authors]]
name = "Gopi Krishnan"
email = "gopi@effy.co.in"

[[project.authors]]
name = "Maanaesh Swamy"
email = "maanaesh.s@effy.co.in"

[build-system]
requires = [ "hatchling", "setuptools", "wheel"]
build-backend = "hatchling.build"

[project.scripts]
freshdesk-mcp = "freshdesk_mcp.server:main"
